// This is a placeholder. Replace with FlutterFire CLI generated file.
// Run: flutterfire configure
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';


// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwR53G0hdbmUo4o7U2BySKb_szuan4Kc',
    appId: '1:749225066447:android:11e47d0e6b49e477971cba',
    messagingSenderId: '749225066447',
    projectId: 'adminpanel-157ff',
    storageBucket: 'adminpanel-157ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpl-e9wp_evzKUhY4ydM0Sv4WWiIh778s',
    appId: '1:749225066447:ios:24ddcd2c5216a2e2971cba',
    messagingSenderId: '749225066447',
    projectId: 'adminpanel-157ff',
    storageBucket: 'adminpanel-157ff.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );
}
